# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(00b94053-e9b5-4aa2-9c33-f080dceee7ad)'
    appType: 'webAppLinux'
    WebAppName: 'exampleappjci'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

-task: PublishBuildArtifacts@4